import json
import re
from pathlib import Path

from app import schemas
from app.main import app

OLOVOICE_DIR = Path(__file__).resolve().parent.parent / "olovoice"

CAMEL_CASE_RE = re.compile(r"^[a-z][a-zA-Z0-9]*$")

REQUEST_MODEL_BY_TOOL = {
    "check_availability": schemas.CheckAvailabilityRequest,
    "create_reservation": schemas.CreateReservationRequest,
    "get_reservation": schemas.GetReservationRequest,
    "cancel_reservation": schemas.CancelReservationRequest,
    "search_menu": schemas.SearchMenuRequest,
}


def _json_files() -> list[Path]:
    return sorted(OLOVOICE_DIR.glob("*.json"))


def _load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def _registered_paths() -> set[str]:
    # app.routes isn't a reliable flat list across FastAPI versions (some
    # resolve included routers lazily); the OpenAPI schema always reflects
    # the fully-resolved route tree.
    return set(app.openapi()["paths"].keys())


def test_json_files_exist_and_parse():
    files = _json_files()
    assert len(files) >= 2
    for f in files:
        _load(f)  # raises on invalid JSON


def test_tools_use_https_camelcase_keys_and_real_routes():
    tools = _load(OLOVOICE_DIR / "tools.json")
    paths = _registered_paths()
    assert len(tools) == len(REQUEST_MODEL_BY_TOOL)

    for tool in tools:
        assert tool["webhookUrl"].startswith("https://"), tool["name"]

        for key in tool.keys():
            assert CAMEL_CASE_RE.match(key), f"{tool['name']}: bad top-level key {key!r}"

        route_path = tool["webhookUrl"].split("YOUR_PUBLIC_DOMAIN", 1)[1]
        assert route_path in paths, f"{tool['name']}: route {route_path} not registered"

        assert tool["method"] == "POST"
        assert tool["includeMetadata"] is True
        assert tool["metadataKey"] == "call_context"
        assert tool["timeoutSec"] == 5
        assert tool["speakResult"] is False
        assert "X-Tool-Secret" in tool["headers"]


def test_tool_schemas_match_pydantic_request_fields():
    tools = _load(OLOVOICE_DIR / "tools.json")

    # both are injected by OloVoice itself, never generated by the model,
    # so neither belongs in inputSchema
    injected_fields = {"tool_call_id", "call_context"}

    for tool in tools:
        model = REQUEST_MODEL_BY_TOOL[tool["name"]]
        model_fields = set(model.model_fields) - injected_fields
        schema_props = set(tool["inputSchema"]["properties"])
        assert schema_props == model_fields, tool["name"]

        model_required = {
            field_name
            for field_name, field in model.model_fields.items()
            if field.is_required() and field_name not in injected_fields
        }
        assert set(tool["inputSchema"].get("required", [])) == model_required, tool["name"]
        assert tool["inputSchema"]["type"] == "object"
        assert tool["inputSchema"]["additionalProperties"] is False


def test_structured_output_schema_has_required_fields():
    schema = _load(OLOVOICE_DIR / "structured_output.json")
    expected_fields = {
        "intent",
        "call_outcome",
        "reservation_code",
        "reservation_date",
        "reservation_time",
        "party_size",
        "tool_succeeded",
        "human_followup_required",
        "failure_reason",
    }
    assert set(schema["properties"]) == expected_fields
    assert set(schema["required"]) == expected_fields
    assert schema["additionalProperties"] is False
    assert schema["properties"]["intent"]["enum"]
    assert schema["properties"]["call_outcome"]["enum"]


def test_no_obvious_real_secret_committed():
    combined = "\n".join(
        f.read_text(encoding="utf-8") for f in OLOVOICE_DIR.rglob("*") if f.is_file()
    )
    suspicious_patterns = [
        r"sk-[A-Za-z0-9]{10,}",
        r"Bearer [A-Za-z0-9._\-]{20,}",
        r"AIza[0-9A-Za-z\-_]{20,}",
    ]
    for pattern in suspicious_patterns:
        assert not re.search(pattern, combined), pattern

    assert "REPLACE_WITH_TOOL_SECRET" in combined
